import type { Simulation } from "./contracts";
export const simulationFixture = (): Simulation => ({
  id: "run-1",
  title: "Рейс 001 · Учебная смена",
  status: "active",
  revision: 1,
  started_at: "2026-09-26T12:00:00Z",
  server_time: "2026-09-26T12:00:00Z",
  elapsed_seconds: 0,
  duration_seconds: 1200,
  location: "service",
  zones: [
    { id: "service", title: "Служебная зона", kind: "service" },
    { id: "salon", title: "Пассажирский салон", kind: "passenger" },
  ],
  stations: [
    {
      id: "moscow",
      title: "Москва",
      arrival_seconds: 0,
      departure_seconds: 30,
      status: "dwell",
    },
    {
      id: "spb",
      title: "Санкт-Петербург",
      arrival_seconds: 1200,
      departure_seconds: 1200,
      status: "upcoming",
    },
  ],
  passengers: [
    {
      id: "p1",
      name: "Пассажир 01",
      zone_id: "salon",
      observation: "Пассажир ждёт помощи.",
    },
  ],
  incidents: [
    {
      id: "request",
      title: "Помощь с багажом",
      kind: "service",
      zone_id: "salon",
      passenger_id: "p1",
      status: "reported",
      severity: 0,
      reported_at_seconds: 0,
      discovered_at_seconds: null,
      first_reaction_seconds: null,
      observation: "Пассажир просит помочь с багажом.",
      facts: [],
      actions: [
        {
          id: "talk",
          label: "Поговорить",
          description: "Уточнить просьбу",
          enabled: true,
          reason: null,
          incident_id: "request",
          zone_id: "salon",
        },
      ],
    },
  ],
  actions: [],
  equipment: [],
  communications: [],
  metrics: {
    safety: 70,
    service: 70,
    regulation: 70,
    communication: 70,
    prioritization: 70,
    average_reaction_seconds: null,
  },
  xp: 0,
  journal: [],
});
