export function debriefFixture() {
  return {
    rule_version: 1,
    session_id: "session-1",
    scenario_id: "demo-service-situation",
    scenario_version: 1,
    title: "Работа с пассажиром",
    completed_at: "2026-09-26T10:00:08Z",
    summary: {
      decision_count: 1,
      timeout_count: 0,
      loyalty_delta: 5,
      safety_delta: 0,
    },
    decisions: [
      {
        sequence: 1,
        decision_id: "decision-1",
        node_id: "request",
        node_text: "Пассажир просит помощь.",
        choice_id: "explain",
        choice_text: "Объяснить порядок действий",
        destination_id: "done",
        destination_text: "Пассажир знает, куда обратиться.",
        decided_at: "2026-09-26T10:00:08Z",
        elapsed_seconds: 8,
        was_timeout: false,
        explanation: "Переход выполнен",
        loyalty: {
          before: 95,
          after: 100,
          delta: 5,
          requested_delta: 10,
          explanation:
            "Спокойный ответ укрепляет доверие. Верхняя граница ограничила прирост.",
        },
        safety: {
          before: 50,
          after: 50,
          delta: 0,
          requested_delta: 0,
          explanation: "Решение не меняет безопасность.",
        },
        competencies: [
          {
            competency_id: "communication",
            before: 0,
            after: 1,
            delta: 1,
            explanation: "Вы объяснили пассажиру следующий шаг.",
          },
        ],
        alternatives: [
          {
            choice_id: "offer",
            text: "Проводить пассажира",
            destination_id: "help",
            explanation: "Личное сопровождение снимает вопрос.",
            available: true,
            loyalty_delta: 5,
            safety_delta: 2,
            competencies: [{ competency_id: "communication", delta: 1 }],
          },
          {
            choice_id: "restricted",
            text: "Открыть служебный проход",
            destination_id: "restricted",
            explanation: "Условия выбора не выполнены.",
            available: false,
            loyalty_delta: 0,
            safety_delta: -10,
            competencies: [],
          },
        ],
        suggestion: {
          text: "Попробуйте предложить сопровождение: оно добавляет безопасность.",
          choice_ids: ["offer"],
        },
        pattern_codes: [] as string[],
      },
    ],
  };
}

export function analyticsFixture() {
  return {
    rule_version: 1,
    total_sessions: 4,
    completed_sessions: 3,
    active_sessions: 1,
    decision_count: 8,
    timeout_count: 2,
    competencies: [
      {
        competency_id: "communication",
        earned_points: 4,
        net_delta: 4,
        positive_decisions: 4,
        negative_decisions: 0,
        opportunities: 5,
        practiced_sessions: 3,
        status: "strength",
        trend: [
          {
            session_id: "s1",
            completed_at: "2026-09-25T10:00:00Z",
            delta: 2,
            earned_points: 2,
            cumulative_points: 2,
          },
          {
            session_id: "s2",
            completed_at: "2026-09-26T10:00:00Z",
            delta: 2,
            earned_points: 2,
            cumulative_points: 4,
          },
        ],
      },
      {
        competency_id: "coordination",
        earned_points: 0,
        net_delta: -2,
        positive_decisions: 0,
        negative_decisions: 2,
        opportunities: 3,
        practiced_sessions: 2,
        status: "growth_area",
        trend: [
          {
            session_id: "s1",
            completed_at: "2026-09-25T10:00:00Z",
            delta: -2,
            earned_points: 0,
            cumulative_points: 0,
          },
        ],
      },
      {
        competency_id: "service",
        earned_points: 0,
        net_delta: 0,
        positive_decisions: 0,
        negative_decisions: 0,
        opportunities: 1,
        practiced_sessions: 1,
        status: "insufficient_data",
        trend: [],
      },
    ],
    strengths: ["communication"],
    weaknesses: ["coordination"],
    patterns: [
      {
        code: "timeout",
        title: "Время истекает до решения",
        description: "Решение принято после срока в нескольких попытках.",
        count: 2,
        session_count: 2,
        recurring: true,
        advice: "Сначала оцените срочность запроса.",
      },
    ],
    scenarios: [
      {
        scenario_id: "demo-service-situation",
        scenario_version: 1,
        title: "Работа с пассажиром",
        attempts: 3,
        completed: 3,
        active: 0,
        timeout_count: 2,
        average_duration_seconds: 32.5,
        average_loyalty: 60,
        average_safety: 48,
      },
      {
        scenario_id: "new",
        scenario_version: 2,
        title: "Новая ситуация",
        attempts: 1,
        completed: 0,
        active: 1,
        timeout_count: 0,
        average_duration_seconds: null,
        average_loyalty: null,
        average_safety: null,
      },
    ],
  };
}
